package edu.uga.cs.geographyquiz;

import android.annotation.TargetApi;
import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.os.Build;
import android.util.Log;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

public class GeographyQuizData {

    //Private members
    private Context context;
    private SQLiteDatabase db;
    private SQLiteOpenHelper geographyQuizzesDbHelper;
    private String[] allColumns = {GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_ID,
    GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION1, GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION2,
            GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION3, GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION4,
            GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION5, GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION6,
    };

    //Constructor
    public GeographyQuizData(Context context){
        this.geographyQuizzesDbHelper = GeographyQuizDBHelper.getInstance(context);
        this.context = context;
    }

    //Open the database connection
    public void open(){
        db = geographyQuizzesDbHelper.getWritableDatabase();
    }

    //Close the database connection
    public void close(){
        if (geographyQuizzesDbHelper != null){
            geographyQuizzesDbHelper.close();
        }
    }

    //Method for storing a Geography Quiz into the database
    public GeographyQuiz storeGeographyQuiz(GeographyQuiz geographyQuiz){

        ContentValues values = new ContentValues();

        values.put(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION1, geographyQuiz.getQuestion_1());
        values.put(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION2, geographyQuiz.getQuestion_2());
        values.put(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION3, geographyQuiz.getQuestion_3());
        values.put(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION4, geographyQuiz.getQuestion_4());
        values.put(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION5, geographyQuiz.getQuestion_5());
        values.put(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION6, geographyQuiz.getQuestion_6());
        values.put(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_SCORE, geographyQuiz.getScore());
        values.put(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_DATE, geographyQuiz.getDate());

        //Insert the new row into the database table
        //The id Primary Key will be automatically generated by the database system
        long id = db.insert(GeographyQuizDBHelper.TABLE_GEOGRAPHYQUIZZES, null, values);

        //Store the id in the geography quiz instance, as it is now persistent
        geographyQuiz.setId(id);

        return geographyQuiz;
    }

    //Method for retrieving all geography quizzes from the database
    public List<GeographyQuiz> retrieveGeographyQuizzes(){
        ArrayList<GeographyQuiz> geographyQuizzes = new ArrayList<>();
        Cursor cursor = null;

        cursor = db.query(GeographyQuizDBHelper.TABLE_GEOGRAPHYQUIZZES, allColumns, null, null, null, null, null);
        while (cursor.moveToNext()){
            //Query the values from one row, iterating over each row
            long id = cursor.getLong(cursor.getColumnIndex(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_ID));
            int question_1 = cursor.getInt(cursor.getColumnIndex(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION1));
            int question_2 = cursor.getInt(cursor.getColumnIndex(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION2));
            int question_3 = cursor.getInt(cursor.getColumnIndex(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION3));
            int question_4 = cursor.getInt(cursor.getColumnIndex(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION4));
            int question_5 = cursor.getInt(cursor.getColumnIndex(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION5));
            int question_6 = cursor.getInt(cursor.getColumnIndex(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_QUESTION6));
            int completed = cursor.getInt(cursor.getColumnIndex(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_COMPLETED));
            int score = cursor.getInt(cursor.getColumnIndex(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_SCORE));
            String date = cursor.getString(cursor.getColumnIndex(GeographyQuizDBHelper.GEOGRAPHYQUIZZES_COLUMN_DATE));

            //Create Geography Quiz object with current values
            GeographyQuiz geographyQuiz = new GeographyQuiz(question_1,question_2,question_3,
                    question_4,question_5,question_6);
            geographyQuiz.setId(id);
            geographyQuiz.setCompleted(completed);
            geographyQuiz.setScore(score);

            //Append current row's data to the ArrayList
            geographyQuizzes.add(geographyQuiz);
        }

        return geographyQuizzes;
    }

    @TargetApi(Build.VERSION_CODES.M)
    public GeographyQuiz retrieveById(int id){
        try {

            //Get readable database
            db = geographyQuizzesDbHelper.getReadableDatabase();

            Cursor cursor = null;
            cursor = db.rawQuery("SELECT id,q1,q2,q3,q4,q5,q6,completed,score,date FROM geographyquizzes WHERE id="+id,null);

            GeographyQuiz geographyQuiz = new GeographyQuiz();
            while (cursor.moveToNext()){

                //Set quiz id
                geographyQuiz.setId(cursor.getInt(0));
                //Set quiz question references
                geographyQuiz.setQuestion_1(cursor.getInt(1));
                geographyQuiz.setQuestion_2(cursor.getInt(2));
                geographyQuiz.setQuestion_3(cursor.getInt(3));
                geographyQuiz.setQuestion_4(cursor.getInt(4));
                geographyQuiz.setQuestion_5(cursor.getInt(5));
                geographyQuiz.setQuestion_6(cursor.getInt(6));
                //Set number of completed questions for quiz
                geographyQuiz.setCompleted(cursor.getInt(7));
                //Set current score for quiz
                geographyQuiz.setScore(cursor.getInt(8));
                //Set date for quiz
                LocalDate date = LocalDate.parse(cursor.getString(9));
                geographyQuiz.setDate(date);

                cursor.close();
                return geographyQuiz;
            }

            return null;
        }catch (Exception e){
            Log.d("GEOG_QUIZ",e.toString());
            return null;
        }
    }

    /**
     * Method that generates and returns a quiz with unique countries */
    public GeographyQuiz generateQuiz(){

        GeographyQuestionData questionData = new GeographyQuestionData(context);

        List<GeographyQuestion> questionList = questionData.retrieveGeographyQuestions();
        GeographyQuiz quiz = new GeographyQuiz();
        //While quiz is not unique, keep trying to find random countries for questions
        boolean keepGoing = true;
        while (keepGoing){
            //Get a random id to check
            int random = (int) (Math.random() * questionList.size());
            //If the question is not in the quiz yet, add it
            if ((!hasQuestion(quiz, (int) random))){
                quiz.setQuestion_1(random);
            }

            //Get a random id to check
            random = (int) (Math.random() * questionList.size());
            //If the question is not in the quiz yet, add it
            if ((!hasQuestion(quiz, (int) random))){
                quiz.setQuestion_2(random);
            }

            //Get a random id to check
            random = (int) (Math.random() * questionList.size());
            //If the question is not in the quiz yet, add it
            if ((!hasQuestion(quiz, (int) random))) {
                quiz.setQuestion_3(random);
            }

            //Get a random id to check
            random = (int) (Math.random() * questionList.size());
            //If the question is not in the quiz yet, add it
            if ((!hasQuestion(quiz, (int) random))) {
                quiz.setQuestion_4(random);
            }

            //Get a random id to check
            random = (int) (Math.random() * questionList.size());
            //If the question is not in the quiz yet, add it
            if ((!hasQuestion(quiz, (int) random))) {
                quiz.setQuestion_5(random);
            }

            //Get a random id to check
            random = (int) (Math.random() * questionList.size());
            //If the question is not in the quiz yet, add it
            if ((!hasQuestion(quiz, (int) random))){
                quiz.setQuestion_6(random);
            }

            //If the quiz is unique, break and return it, otherwise continuing generating random questions
            if (isUnique(quiz)){
                break;
            }
        }
        //Store quiz
        this.storeGeographyQuiz(quiz);
        return quiz;
    }

    private boolean hasQuestion(GeographyQuiz quiz, long questionId){
        if (questionId == quiz.getQuestion_1() || questionId == quiz.getQuestion_2() ||
                questionId == quiz.getQuestion_3() || questionId == quiz.getQuestion_4() ||
                questionId == quiz.getQuestion_5() || questionId == quiz.getQuestion_6()){
            return true;
        }
        return false;
    }

    private boolean isUnique(GeographyQuiz quiz){
        List<Integer> questionList = new LinkedList<>();
        questionList.add((int)quiz.getQuestion_1());
        if (questionList.contains(quiz.getQuestion_2())) return false;
        questionList.add((int)quiz.getQuestion_2());
        if (questionList.contains(quiz.getQuestion_3())) return false;
        questionList.add((int)quiz.getQuestion_3());
        if (questionList.contains(quiz.getQuestion_4())) return false;
        questionList.add((int)quiz.getQuestion_4());
        if (questionList.contains(quiz.getQuestion_5())) return false;
        questionList.add((int)quiz.getQuestion_5());
        if (questionList.contains(quiz.getQuestion_6())) return false;
        questionList.add((int)quiz.getQuestion_6());

        return true;
    }
}
